name: gyakorlat
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - ipykernel=5.5.0
  - numpy=1.20.1
  - matplotlib=3.3.4
  - pytorch=1.6.0
  - torchvision=0.7.0
  - tqdm=4.59.0
  - imgaug=0.4.0
#  - nodejs=20.9.0
#   - ipywidgets
  - pillow
#  - jupyterlab
